# Generated by Django 2.2.6 on 2019-10-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text='<b>Markdown</b> supported'),
        ),
    ]
